ALIGN_CODE_SEQUENCE: FullSeq
CHAIN_ID: A
BLK_CHAIN_ID: B
CUSTOM_INIFILE_BASENAME: precomputed_ini.pdb
CUSTOM_RSRFILE_BASENAME: precomputed_rsr.rsr
FASTA_FILE_BASENAME: sequence_full.fasta
SS2_FILE_BASENAME: P1_NCL_secondary_structure.ss2
MANUAL_ALIGNMENT_BASENAME: manual_template_FullSeq.ali
MANUAL_ALIGNMENT_CDE_BASENAME: manual_template_FullSeq_cde.ali
MODELLER_CORES: 10
TOTAL_PARALLEL_JOBS: 10
TOTAL_HOMOLOGY_MODELS: 10000
TOP_MODELS_FOR_REFINEMENT: 20
LOOP_MODELS_PER_TARGET: 10
NUM_BEST_FINAL_MODELS: inf
PERFORM_PSIPRED_PREDICTION: true
PSIPRED_EMAIL: richard.lopezc@uah.es
PSIPRED_POLL_INTERVAL: 60
USE_MANUAL_ALIGNMENT: true
BLOCK_REPULSION_RADIUS: 5.0
REFINE_FLANKS_DURING_AUTOMODEL: true
MOBILE_FLANK_RESIDUES: 5
EXECUTION_PARADIGM: prism-power
USE_MANUAL_OPTIMIZATION_SELECTION: false
MANUAL_OPTIMIZATION_RESIDUES: []
PDB_TEMPLATE_FILES_NAMES:
- 9CB5_renum_HETATM.pdb
- AF_renum.pdb
PRISM_POWER_SETTINGS:
  precalculation:
    9CB5_DS_renum_HETATM-B.pdb: 1000
    2fc9_DS_renum.pdb: 500
    2fc8_DS_renum.pdb: 500
    AF-P19338-F1-model_v6_DS_renum.pdb: 1
  precomputed:
    9CB5_DS_renum_HETATM-B.pdb: 100
    2fc9_DS_renum.pdb: 50
    2fc8_DS_renum.pdb: 50
    AF-P19338-F1-model_v6_DS_renum.pdb: 1
INPUT_DIR_NAME: input
MODELING_RESULTS_DIR_NAME: modeling_results
PSIPRED_RESULTS_DIR_NAME: psipred_results
